### ISSUE TITLE
Double check force conventions

### ISSUE THREAD

**Issue by rmodrak** [uafgeotools/mtuq#112]
Here's what I was aiming for:

`(F0, theta, h)`
Uniform parameterization for forces, where `F0` is magnitude of force in Newtons, `theta` is azimuth in degrees counterclockwise from east, and `h` is cos(colatitude)

function `to_xyz`
converts from (F0,theta,h) to east-north-up
https://github.com/uafgeotools/mtuq/blob/cdfd68669c4cee84f4e8796321ab69f00affe65f/mtuq/util/lune.py#L111

function `to_rtp`
converts from (F0,theta,h) to up-south-east
https://github.com/uafgeotools/mtuq/blob/cdfd68669c4cee84f4e8796321ab69f00affe65f/mtuq/util/lune.py#L117

**Comment by rmodrak** [comment]
Possible improvements:
- define azimuth as counterclockwise from South, which would make cartographic plotting more natural
- use `(F0, azimuth, h)` because `theta` is already used elsewhere in the code

**Comment by rmodrak** [comment]
Scratch the previous ideas.  Now leaning to the following:

(F0, phi, h)
Uniform parameterization for forces, where F0 is magnitude of force in Newtons, phi is azimuth in degrees counterclockwise from east, and h is cos(colatitude).

For internal arrays and linear combintations, `F0, phi, h` are converted to up-south-east coordinates `r, t, p` via:
https://github.com/uafgeotools/mtuq/blob/cdfd68669c4cee84f4e8796321ab69f00affe65f/mtuq/util/lune.py#L117

For plotting, `h, `theta` are converted to `lat, lon` via:
https://github.com/rmodrak/mtuq/blob/57ceb665551e22ec2baea7ed96a2eb011ab95edf/mtuq/graphics/uq_force.py#L238

Now variable names and conventions are consistent between forces and moment tensors.  In particular, the variable name phi is consistent with the "physics" spherical coordinates convention used in all the Tape & Tape moment tensor papers.

**Comment by rmodrak** [comment]
We need a test case exactly like this: https://github.com/krischer/instaseis/issues/77

**Comment by thurinj** [comment]
#193 discusses a convention issue with Instaseis Radial Force component.
