### ISSUE TITLE
Passing the absolute filename may raise errors

### ISSUE THREAD

**Issue by Liang-Ding** [uafgeotools/mtuq#161]
Multiple lines with the **_'tmp.'+filename+..._** in the function **def _plot_beachball_gmt**(...) in the script [**beachball.py**](https://github.com/uafgeotools/mtuq/blob/ed6330ca1972be410c03149d1a953951457c58e4/mtuq/graphics/beachball.py) may raise errors when passing the absolute filename.

**Comment by rmodrak** [comment]
Very helpful, thanks Liang.  Adding this to the list of things to address next month.

**Comment by rmodrak** [comment]
I think this fixes it, but let me know if see anything else. -Ryan
https://github.com/rmodrak/mtuq/commit/38d9755668f5831c273ee7ba7067b9571ca605bd
