### ISSUE TITLE
TODO: Add slices option into mtuq double couple misfit map plots

### ISSUE THREAD

**Issue by thurinj** [uafgeotools/mtuq#167]
@SeismoFelix raised an interesting point concerning the current implementation of the double-couple misfit map. 
It currently relies on the built-in `min()` method in `xarray.DataArray` format, in which the results are stored.
What this does is that it aggregates the minimum misfit values along all dimensions of the misfit space.

It would be nice to add an option that first isolates the misfit cube (in _strike_, _dip_, and _slip_ dimensions) containing the minimum misfit, and then return the three slices that cross the minimum misfit value. 

This is the function that needs to be updated:
https://github.com/uafgeotools/mtuq/blob/c3e2e7652cc08ed9e450c292b84e3fc6e1710b93/mtuq/graphics/uq/double_couple.py#L17

potentially by adding an alternative function to
https://github.com/uafgeotools/mtuq/blob/c3e2e7652cc08ed9e450c292b84e3fc6e1710b93/mtuq/graphics/uq/double_couple.py#L51

**Comment by rmodrak** [comment]
Sorry I missed this earlier.  I don't receive GitHub notifications at work, because my personal email is blocked there.

**Comment by rmodrak** [comment]
Taking a stab at it here
https://github.com/uafgeotools/mtuq/pull/168

and in particular here
https://github.com/rmodrak/mtuq/blob/191706fd41360821719fae4c959e38cc30c2695e/mtuq/graphics/uq/double_couple.py#L179

For minimizing in the conventional way:
`plot_misfit_dc(filename, dataarray)`
`plot_misfit_dc(filename, dataarray, squeeze='min')`

For slicing
`plot_misfit_dc(filename, dataarray, squeeze='slice_min')`

Note the squeeze argument works well with all the other `uq/double_couple.py` functions.  For example, you could do
`plot_variance_reduction_dc(filename, dataarray, squeeze='slice_max')`

**Comment by rmodrak** [comment]
plot_misfit_dc(filename, dataarray, squeeze='min')
![20090407201255351DC_misfit](https://user-images.githubusercontent.com/4483402/168183609-6f809dc8-6816-4c37-b979-bf52f9071ac8.png)


 plot_misfit_dc(filename, dataarray, squeeze='slice_min')
![20090407201255351DC_misfit_slice](https://user-images.githubusercontent.com/4483402/168183648-02a5cc7c-72a6-4a6b-b394-7a7d9bbed406.png)

**Comment by rmodrak** [comment]
Added previously.
