### ISSUE TITLE
station distance labels (deg or km)

### ISSUE THREAD

**Issue by carltape** [uafgeotools/mtuq#179]
On the waveform fits plots, the station distance is listed in km. When stations are >3000 km or so, it makes sense to list the station distance as an arc-distance in degrees.

**Comment by rmodrak** [comment]
I've started adding an optional argument `station_label_units` with the following choices `'m'`, `'km'`, `'deg'`.  

(If you choose to display distance in degrees though, there is the possible unintended side of confusion between distance and azimuth, which is also displayed in degrees?)

**Comment by rmodrak** [comment]
Implemented via `station_label_units` keyword argument in latest pull request
