### ISSUE TITLE
Data weights not implemented correctly in C/Python misfit function

### ISSUE THREAD

**Issue by rmodrak** [uafgeotools/mtuq#185]
MTUQ includes an [option](https://github.com/rmodrak/mtuq/blob/d36fba83dda8aa2afd4aa7527a42a8b8f18ed8ad/mtuq/process_data.py#L128) to read a [CAPUAF-style text file](https://github.com/uafgeotools/capuaf/blob/2d847befc43fb22f5e5b205aba09aeec4f900acf/cap.pl#L159) with user-supplied data weights and phase picks.  

Jonas K (@kintner92) discovered that, while fully implemented in the pure Python misfit functions, data weights are not fully implemented for the Python/C misfit function.  More precisely, user-supplied weights get cast to 0s or 1s, so that rather than a data weighting matrix per se, only a binary mask is implemented.

A bugfix is required so that any nonnegative scalar can be used as a weight (not just 0s and 1s).

**Comment by thurinj** [comment]
Found an easy fix for that:

To the following function https://github.com/uafgeotools/mtuq/blob/19f7394a4f336607c737e1b981d2b7d2232c0e36/mtuq/misfit/waveform/level2.py#L182

adding this else statement seems to perfectly do the trick. We might want to change the function name to _get_weight then.
```python3
            if len(stream)==0:
                mask[_i, _j] = 0.
            else :
                mask[_i, _j] = stream[0].attrs.weight
```

I am finishing up a couple of tests and I will open a PR for the fix.

**Comment by thurinj** [comment]
Here are three test cases. 
I've put the weights to 0.01 for each of the traces, except for the one circled in green which has a weight of 6. 
![20220115041446000FMT_waveforms_body_solution_006](https://user-images.githubusercontent.com/63735192/216845955-43d5beca-fec8-4144-a805-b1b68ba8f9a6.png)
![20220115041446000FMT_waveforms_body_solution_600](https://user-images.githubusercontent.com/63735192/216845958-f0afa233-0eb6-4fc6-8bcf-d4eb1bccdec2.png)
![20220115041446000FMT_waveforms_body_solution](https://user-images.githubusercontent.com/63735192/216845959-0e6151d3-e711-4bf5-8f82-b79b577cfcfd.png)

The three solutions are what we expect, with the data fit being optimal for the circled trace.

**Comment by rmodrak** [comment]
Included Julien's fix in latest pull request
