### ISSUE TITLE
plot misfit against omega

### ISSUE THREAD

**Issue by Rinku-274** [uafgeotools/mtuq#186]
Hello everyone,
I want to plot each value of misfit against omega (angular distance between two MTs) for both regular as well as random points. Is there any code available in MTUQ for this? I have not found such function inside MTUQ. Hope you will look into the matter.

Thank you.
Rinku

**Comment by vsilwal** [comment]
It appears that omega values are being calculated over here:
https://github.com/uafgeotools/mtuq/blob/1b3481e31f0e59310393bf523605b87ff9602f83/mtuq/graphics/uq/omega.py#L104-L110

misfit vs omega plot can easily be generated from this.

Maybe the more direct question would be if mtuq generates figures 7(c)-(f) of SilwalTape2016 (https://agupubs.onlinelibrary.wiley.com/cms/asset/4927629b-598b-499f-af1f-5bd6e9946e0f/jgrb51546-fig-0007-m.jpg)

**Comment by carltape** [comment]
For Figures 7c-f, the original instructions from capuaf and GMT plotting are from this example:
https://github.com/uafgeotools/capuaf/blob/master/EXAMPLES/README_uncertainty
The basic calculations for omegadc are in Matlab scripts here:
https://github.com/carltape/mtbeach/tree/master/matlab
See [omegadcpdf.m](https://github.com/carltape/mtbeach/blob/master/matlab/omegadcpdf.m) and [plot_omegadc.m](https://github.com/carltape/mtbeach/blob/master/matlab/plot_omegadc.m) for the DC case.
The probability density function for omega for a fixed source type can be seen in plot_omega.m (see Tape and Tape, 2017); the mesa shape is the case when the source type is a DC. We would like to have these older Matlab and GMT plotting capabilities ported to Python and pyGMT.

**Comment by rmodrak** [comment]
Yes, it looks like there's a rough sketch of the the angular distance plotting functions, which could benefit from further testing and improvement.  

It looks like the following functions currently work for _uniformly-drawn full moment tensor grids_:
[plot_pdf](https://github.com/rmodrak/mtuq/blob/d36fba83dda8aa2afd4aa7527a42a8b8f18ed8ad/mtuq/graphics/uq/omega.py#L15)
[plot_cdf](https://github.com/rmodrak/mtuq/blob/d36fba83dda8aa2afd4aa7527a42a8b8f18ed8ad/mtuq/graphics/uq/omega.py#L39)

It's possible that _uniformly-drawn double couple grids_ might already work, we'd have to check.

In addition to these likelihood functions, it could be straightforward to add a `plot_omega_misfit` function as well.  Perhaps at that point, we could revisit and finalize the naming convention for these angular distance plotting functions. 

I think this covers all the cases raised by Vipul and Carl, but let me know if I'm forgetting anything. 

As Rinku was suggesting, it might eventually be possible to perform the integration over regularly-spaced grids, but a more involved integration rule/aliasing safeguards may be necessary.

**Comment by rmodrak** [comment]
Hoping to start digging into this and other GitHub issues soon.

One final thing-- in computing these marginal distributions over angular distance, we normally integrate outward from the maximum likelihood estimate.  However, another procedure with practical importance for explosion monitoring involves in integrating outward from an isotropic explosion.  (To support this, it may be necessary to modify or generalize some of the existing functions?)

**Comment by rmodrak** [comment]
Please feel free to reopen if necessary
