### ISSUE TITLE
Need to update conda installation instructions

### ISSUE THREAD

**Issue by rmodrak** [uafgeotools/mtuq#187]
due to changes in conda itself, these installation instructions no longer work:
https://uafgeotools.github.io/mtuq/install/env_conda.html

Here are details about how conda installation fails:
https://github.com/rmodrak/mtuq/actions/runs/3247505451/jobs/5327561521

it seems we encounter this only because we load NumPy libraries in Python/C extensions
https://github.com/uafgeotools/mtuq/blob/9c56a974a463a204518e4a54bb8c377df57b1322/setup.py#L102

I think a relatively quick fix should be possible...

**Comment by rmodrak** [comment]
these instructions are now updated:
 https://uafgeotools.github.io/mtuq/install/env_conda.html

and the CI tests now pass, so I'll accept the pull request soon:
https://github.com/uafgeotools/mtuq/pull/188

**Comment by rmodrak** [comment]
Julien (@thurinj) points out:

conda develop may no longer be supported by conda (see [here](https://urldefense.com/v3/__https://github.com/conda/conda-build/issues/4251__;!!Bt8fGhp8LhKGRg!F3s1gWn4GY-0leSrscHGpPb6WjyUjMNutwEDv3TBd29li1NrQG3sCMGD2KvC9x8UV3Rcix2_arCy55qeHkY$)).

**Comment by rmodrak** [comment]
Thanks Julien for the helpful info.  I wasn't aware `conda develop .` had so many problems.  

I agree, it seems like we should ultimately go back to `pip install -e .`

To do this, we would need an alternative workaround for the installation problem described at top.  (Here again are the [details](https://github.com/rmodrak/mtuq/actions/runs/3247505451/jobs/5327561521) about how the installation failed.)

I am describing the issue correctly?  Please let me know if there are any comments/corrections.

**Comment by rmodrak** [comment]
Looking closely at conda reveals a lot of apparent problems.

For example, I start by downloading the latest version of miniconda for MacOS Intel from this site:
https://docs.conda.io/en/main/miniconda.html

But then after running the installation script and creating an environment I get
```
==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 22.9.0
```

So I try updating to version 22.9.0: 
```
conda update -n base -c defaults conda
```

But this apparently breaks things so that the following fails
```
conda create --name $ENV python=3
```

**Comment by thurinj** [comment]
Hi Ryan,

My suggestion for the installation instructions under the most recent version of conda would be to do the following:


Download the MTUQ source code:
```bash 
git clone https://github.com/uafgeotools/mtuq.git
cd mtuq
```

Use conda to create a Python environment and install mtuq:
```bash
conda config --prepend channels conda-forge
conda env create -n mtuq --file env.yaml
```
The `env.yaml` file will install mtuq in editable mode by default, and install all of mtuq's dependencies.

Unpack seismic waveforms used by examples:
```bash
bash ./data/examples/unpack.bash
bash ./data/tests/unpack.bash
```

Finally, install PyGMT:
```bash
conda install pygmt
```

I think by default, the environment will be a python 3.x version. But we can still specify this
```bash
conda env create -n mtuq_ryan --file env.yaml python=3
```
I cannot replicate the error for `conda create --name mtuq python=3` on my condo installation (also version 22.9.0)

**Comment by rmodrak** [comment]
Hi Julien,
Thanks for the detailed suggestion-- I've tried implementing it in the most recent pull request. 
If you see any opportunity for further improvement, please me know.
Thanks,
Ryan

**Comment by bch0w** [comment]
Hope I can tack onto this thread instead of starting a new issue. Not sure if this is known already but I didn't see it posted anywhere on the install instructions: seems like instaseis is not compatible with the ARM architecture of the M1 Mac? 

```bash
(mtuq) [mtuq] $ conda env update --file env.yaml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - instaseis
```

Attempted on an M1 Mac running macOS 13.0, Conda 4.12.0, Python3.11 (also tried 3.8). I was able to successfully install MTUQ on my Linux machine so I know the install instructions should work. 

@thurinj are you able to install instaseis/MTUQ on your M1?

**Comment by rmodrak** [comment]
Thanks for pointing this out Bryant.

I recently ordered an M2 mac, so I hope to try it myself as well.  (It will
be my first time using a non-intel Mac.)

If I remember, instaseis installation has often been tricky, with past
errors related to Python+Fortran acceleration.

**Comment by rmodrak** [comment]
Update: MTUQ installation has been working well for about a year now.  PyGMT seems to be more mature and PyGMT installation without problems.  The main remaining issue now is that Instaseis does not install on new Mac hardware.   Closing this now, but feel free to open a more up-to-date issue if desired.
