### ISSUE TITLE
display force sphere on waveform fits plot

### ISSUE THREAD

**Issue by carltape** [uafgeotools/mtuq#197]
The waveform fits plots for moment tensors has a nice beachball at the upper left. When the user is trying a force source, we need to display a "force sphere" showing a symbol (dot/circle/symbol) for the best-fitting force direction. W and E meridians need to be indicated somehow. Thank you!

**Comment by rmodrak** [comment]
Are you thinking of the device that we already use for conveying force uncertainties?

Or do we want something like the following figure from Euler angles wikipedia description?  
![image](https://user-images.githubusercontent.com/4483402/219978940-202be8b4-99bb-4680-a079-e2184b15ba02.png)
Just replace (z, x, y) with (up, south, east).  Also we would only need theta and psi, not phi.

**Comment by carltape** [comment]
I was thinking of just redisplaying the existing force sphere, but without the colored misfit map. Just the global minimum.

**Comment by rmodrak** [comment]
cbab9ffa467c666ce5651f21e84032d3eca7db72

<img width="774" alt="Screen Shot 2023-02-20 at 1 19 07 AM" src="https://user-images.githubusercontent.com/4483402/220050602-4bec083b-b924-41ef-a8f7-289bc69c42c4.png">
