### ISSUE TITLE
Read in SPECFEM Green's Functions Database for Force

### ISSUE THREAD

**Issue by ammcpherson** [uafgeotools/mtuq#203]
Hello,

We would like the capability to read in SPECFEM3D-generated, source-side force Green's Functions. Currently, MTUQ is able to read in [SPECFEM3D source-side MT Green's Functions](https://github.com/uafgeotools/mtuq/blob/master/mtuq/greens_tensor/SPECFEM3D.py#L46) and compute synthetics from them. MTUQ also has the capability to [use AxiSEM force Green's Functions](https://github.com/uafgeotools/mtuq/blob/master/mtuq/greens_tensor/AxiSEM.py#L109) to compute synthetics.

The end goal would be something similar to what @SeismoFelix has established [here](https://github.com/uafgeotools/mtuq_supp/tree/main/greens_functions_libraries/specfem/cartesian_MT), in which we would like to compute source-side GFs in a chosen velocity model, and use them in an inversion with MTUQ.

Thank you,
Amanda

**Comment by rmodrak** [comment]
Please feel free to take a stab-- 

I think you would just have to decide on the expected file names for force Green's functions, and then add some lines of code in the following two places:

 - https://github.com/uafgeotools/mtuq/blob/453610fa8f193e13a33e2df7867ade472824b471/mtuq/io/clients/SPECFEM3D_SAC.py#L115

- https://github.com/uafgeotools/mtuq/blob/453610fa8f193e13a33e2df7867ade472824b471/mtuq/greens_tensor/SPECFEM3D.py#L81

In making both of the above additions, I believe you could closely follow the immediately preceding implementation for moment tensors.

If I remember, there was some earlier discussion by email about possible force filenames-- maybe something like the following suffixes?

- `.Fr.sac`
- `.Ft.sac`
- `.Fp.sac`

**Comment by ammcpherson** [comment]
I will make some modifications and submit a pull request hopefully soon. I support your proposed suffixes.
