### ISSUE TITLE
list location code (net.sta.loc) in waveform fits plot

### ISSUE THREAD

**Issue by carltape** [uafgeotools/mtuq#210]
Station location codes can be important, especially for data sets using GSN stations, which have multiple sensors and location codes. It would be good to ensure that location codes are tracked and also displayed on the waveform fits plot and wherever else the station label is used. Many location codes will be blank; if they're not blank, they're often 00 or 10. Not urgent.

**Comment by rmodrak** [comment]
Is this the desired behavior in lines 18-21?
https://github.com/uafgeotools/mtuq/blob/5ff1a724b595f8096e5466cef7803231be6cc0a1/mtuq/graphics/annotations.py#L18
