### ISSUE TITLE
annotations on waveform fits plots

### ISSUE THREAD

**Issue by carltape** [uafgeotools/mtuq#221]
Please consider some additional annotations for the MTUQ waveform fits plots. This excerpt from Figure S2 of Alvizuri and Tape (2018), generated with the older code, includes some items that we found useful.
<img width="867" alt="Screen Shot 2023-08-22 at 4 01 21 PM" src="https://github.com/uafgeotools/mtuq/assets/4455456/fabdcb49-d9ee-4b64-9254-a9d38a17291f">
It shows the length of the P window and surface wave windows (1s -- not used here; 500 s), the number of stations used (N = 34), the number of P window measurements (Np = 0), and number of surface wave measurements (Ns = 102). Ideally it would list the number of first-motion polarities used in the header, but this information is listed as the 4th text row on the left. So "1 (0.74)" represents the measured polarity (1 = up) and the theoretical amplitude factor for this particular mechanisms (0.74). A theoretical value near 0 would represent a near-nodal station. Thanks.

**Comment by rmodrak** [comment]
Here's one idea--  I think we could make the following two functions "swappable", so to speak.

[add_trace_labels()](https://github.com/uafgeotools/mtuq/blob/ce9aab7f15517b68d9cd420176449d84275c00c9/mtuq/graphics/waveforms.py#L553)
[add_station_labels()](https://github.com/uafgeotools/mtuq/blob/ce9aab7f15517b68d9cd420176449d84275c00c9/mtuq/graphics/waveforms.py#L523)

Then users could customize annotations however they like by passing these functions as arguments to the higher level waveform plotting functions.  Perhaps this could be a workable solution?

**Comment by carltape** [comment]
That flexibility would be nice, too. Does it address the overall header line -- the one in the figure with "Pwin 1 Swin 500 N 34 Np 0 Ns 102"? The one item that should not be optional is the length of the time windows, since (without a scale bar) the viewer cannot tell how much time is displayed in the waveforms. (They can guess from the bandpass listed.) On a related note, given the recent tests with source duration, it might be good to list some text related to what kind of stf (or hdur) is used. And: One cannot tell the difference between a constrained inversion (e.g., deviatoric or double couple) and an unconstrained one. (One could use gamma delta 7 0* for a deviatoric inversion, to distinguish it from gamma delta = 7 0, which would indicate a FMT run that happens to be deviatoric.) Sorry, lots of different thoughts here. The overarching item is that by looking at the waveform fits plot, we should be able to tell most of the key choices for the inversion run.

**Comment by rmodrak** [comment]
- I believe the length of the time windows is now included in the third line of the MTUQ header.  Implementing scale bars is also welcome, if anyone wants to.

- Perhaps the STF information could be added to the second line of the MTUQ header?  A challenge is that sometimes the line gets cut off (e.g. if the Earth model has a long name)

- Agreed, an asterisk to denote a fixed parameter is a great idea.  We would just have to think about how to implement this, since the current plotting function arguments may not provide the necessary information.

- For me, certain closely spaced text can be difficult to read (an issue since childhood), so I like the idea of allowing customization--  allowing both easy-to-read headers and more detailed headers, depending on preference.

**Comment by carltape** [comment]
Ah, you're right about the window lengths! I see them [here](https://github.com/rmodrak/mtbench/blob/FiguresSilwal2016/SerialGridSearch.DoubleCouple.png).
These are "when time permits" items, but good to have the bullets. Thanks.

**Comment by rmodrak** [comment]
Taking a stab at customizable annotations here:
https://github.com/uafgeotools/mtuq/commit/7aa099ac5f686fd7380e56987a8ba0b52eae20b3

**Comment by rmodrak** [comment]
Customizable trace and station annotations added in #224
