### ISSUE TITLE
Need for small QOL improvement for mtuq.event.Force

### ISSUE THREAD

**Issue by thurinj** [uafgeotools/mtuq#223]
The `mtuq.event.Force()` is currently lacking a method that outputs the force vector as a dictionary.

It would be convenient to have a similar method that in [mtuq.event.Force()] (https://github.com/uafgeotools/mtuq/blob/ce9aab7f15517b68d9cd420176449d84275c00c9/mtuq/event.py#L102) 

so that it is easier to build an output dictionary to save it as a JSON file (as in [DetailedAnalysis.py](https://github.com/uafgeotools/mtuq/blob/ce9aab7f15517b68d9cd420176449d84275c00c9/examples/DetailedAnalysis.py))

**Comment by rmodrak** [comment]
@thurinj  Could you please double check that this is correct?

https://github.com/rmodrak/mtuq/blob/db33907642652eb93a91d932004ffe641202065e/mtuq/event.py#L201

**Comment by thurinj** [comment]
Looks good to me!

**Comment by rmodrak** [comment]
Added in #224
