### ISSUE TITLE
meca [error] running serialgridsearch.dc.py example

### ISSUE THREAD

**Issue by jl-miller** [uafgeotools/mtuq#226]
pygmt.exceptions.GMTCLibError: Module 'meca' failed with status code 72:
meca [ERROR]: Option -c is not a recognized common option

**Comment by rmodrak** [comment]
Thanks for this report.  I get this error too after installing mtuq and pygmt from scratch under conda.  In my case, it seems that `conda install pygmt` now results in a very outdated version of pygmt.  Could I ask what is the output of `pygmt.__version__` in your case?

**Comment by jl-miller** [comment]
(mtuq)$ pip show pygmt
Name: pygmt
Version: 0.2.1

>>> print(pygmt.__version__)
v0.2.1

**Comment by rmodrak** [comment]
To update pygmt you could try:
```
conda install 'pygmt>=0.9'
```
After updating in the above manner, I no longer get the pygmt 'meca' error.

**Comment by rmodrak** [comment]
Now added to the documentation:

https://uafgeotools.github.io/mtuq/install/issues.html#troubleshooting-pygmt-installation

Please reopen if there are any other related PyGMT problems.
