### ISSUE TITLE
mtuq install fails due to instaseis & gfortran

### ISSUE THREAD

**Issue by ArthurRodgers** [uafgeotools/mtuq#228]
I tried to install mtuq but it fails because it cannot build instaseis, because gfortran is missing. Should I install gfortran globablly so any conda env can access? What about instaseis? Should this be install in the mtuq conda env or by itself?

I'm not able to install gfortran. I'm running on a relatively new Mac OSX 13.5.2 (Ventura) with Apple M2 Max chip. Is there a way to bypass instaseis and use other Greens functions, say fk?

**Comment by ArthurRodgers** [comment]
Update:

instaseis can be bypassed by commenting it out in `env.yaml` file, then installing mtuq

The plotting issue was related to pygmt. I had pygmt v0.10.0, but the plotting can be fixed by `conda install pygmt=0.9.0`

**Comment by thurinj** [comment]
Hello @ArthurRodgers, unfortunately, I had not faced this issue myself, as I had a working Fortran compiler when I installed `mtuq` on my M1 Mac, but here is an attempt at troubleshooting:

1. **Installing the GNU compilers with `brew`**:

I recommend using the GNU compilers on your system using the `brew` package manager on OSX. Here are the brew main page and installation instructions [https://brew.sh](https://brew.sh), in case you do not have it on your system. It requires having the Command Line Tools (CLT) for Xcode (from `xcode-select --install`).
Once `brew` is installed, you can run 
```
brew install gcc
``` 
to install the compilers. This should work on any Apple silicon chip with OSX Ventura / Sonoma. Hopefully, this solves your issue, and you can install the `mtuq` environment with instaseis without a hitch. 

2. **Trying out Anaconda compilers package**:

If this fails, you can try out the compilers package from Anaconda with one of the following:
```
conda install -c conda-forge compilers
conda install -c "conda-forge/label/cf202003" compilers
```

Or one of the following:
```
conda install -c conda-forge fortran-compiler
conda install -c "conda-forge/label/cf202003" fortran-compiler
```

before you run the `conda env update --file env.yaml` from the install instructions. I have not tried this one out (as I don't have a system without a compiler handy), but it might be a solution.

3. **Removing instaseis dependencies**:

If the other options fail, you can remove the `- instaseis` entry in the env.yaml file and proceed with the installation. This should create the `mtuq` environment without instaseis. You will not be able to use syngine or local Axisem-generated databases, but you should be able to use SPECFEM or FK databases this way. I have just tried installing it this way, and it did complete the installation without errors.

Please let us know if this works, as there are other options to consider, even if nothing here solves your problem (such as running the containerized version of `mtuq` with Docker).

I hope this helps!

**Comment by rmodrak** [comment]
Hi all,

I think instaseis offers major advantages over other methods for reading Green's function, so I'm glad this issue has been created and very interested in finding a solution.

For me, it seems that even if gfortran is in fact installed, pip installation problems can still manifest themselves with gfortran not found errors.  The solution I think lies in the details of the pip installation procedure.

Some progress I think toward this type of underlying solution--

I find that [sttaehler's version](https://github.com/sstaehler/instaseis ) of instaseis installs successfully on an Apple M1 Macbook using
```
conda config --prepend channels conda-forge
conda install numpy obspy
git clone https://github.com/sstaehler/instaseis.git
cd instaseis
pip install -e .
```

Similar to Simon's instaseis M1/M2 compatibility changes, I suspect that updates to mtuq's setup.py file will be necessary on our end.  Planning to work on it this weekend...


-Ryan

**Comment by rmodrak** [comment]
The new pull request #232 

- adds a new yaml environment file that clones instaseis from github.com/sstaehler
- updates clang compiler args in setup.py

With these changes, the following installation procedure now works for me for on an Apple M1 Mac

https://uafgeotools.github.io/mtuq/install/issues.html

Please feel free to try out and reopen if there are any problems.

**Comment by rmodrak** [comment]
Some further notes

- Eventually, when Simon's instaseis pull request (https://github.com/krischer/instaseis/pull/87) gets accepted, we will want to update the instructions
- If someone has an M2 Mac, that would be great to try also
