### ISSUE TITLE
Plotting error function plot_waveforms1

### ISSUE THREAD

**Issue by SeismoFelix** [uafgeotools/mtuq#229]
After running MTUQ only with surface waves, I got this error:

`mtuq/mtuq/graphics/waveforms.py", line 103, inplot_waveforms1   normalize, trace_labels, max_amplitude, total_misfit)NameError: name 'trace_labels' is not defined`

 I guess this happens because when [plotting the waveforms](https://github.com/uafgeotools/mtuq/blob/master/mtuq/graphics/waveforms.py#L103), there is a subroutine expecting a parameter named trace_labels. It seems that the  parameter in this latest version of MTUQ should be named trace_label_writer

**Comment by rmodrak** [comment]
Felix, thanks for reporting this regression.  I will try pushing a fix this weekend.

**Comment by rmodrak** [comment]
Addressed in #233
