### ISSUE TITLE
polarity text label for waveform fits plot

### ISSUE THREAD

**Issue by carltape** [uafgeotools/mtuq#240]
Currently it is not possible to tell from the waveform fits plot whether a first-motion polarity has been used for a given station. The legacy plots look like this (From Alvizuri and Tape, 2018, Figure S2):
![image](https://github.com/uafgeotools/mtuq/assets/4455456/2412c3fc-2a1b-4787-91b1-fd392b8e7292)
The "1 (0.74)" label indicates that the station had a +1 observed polarity that was used in estimating the best-fitting moment tensor. From what I recall, the 0.74 is a synthetic amplitude factor that played a role in down-weighting stations that were nodal (for which you might be more concerned about the 1D model assumption). You can also see the "pol_wt 0.30" listed in the header, indicating the weight of polarities in the misfit function. It would be great to add a +1 or -1 at the left whenever a polarity observation is used. And perhaps a label in the header indicating how many total polarity measurements where used (similar to listing how many total stations, P windows, and Surf windows are used). Thanks.

**Comment by rmodrak** [comment]
Just for reference, through two functions below, trace and station labels can be customized in most any way

https://github.com/rmodrak/mtuq/blob/73ff7690a5356f3ca27964709385dcf131b89c46/mtuq/graphics/annotations.py#L8
https://github.com/rmodrak/mtuq/blob/73ff7690a5356f3ca27964709385dcf131b89c46/mtuq/graphics/annotations.py#L43

**Comment by rmodrak** [comment]
Please feel free to reopen if necessary
