### ISSUE TITLE
Run examples in terminal encountered plot errors

### ISSUE THREAD

**Issue by ZiguoFu** [uafgeotools/mtuq#257]
Dear developers:

        I have installed MTUQ followed the installation guides https://uafgeotools.github.io/mtuq/install/index.html
        When  I run the examples in my terminal using the code:  python SerialGridSearch.DoubleCouple.py, everything goes right except the last plot results. Could you help me debug the errors. 

 
![image](https://github.com/uafgeotools/mtuq/assets/68380266/5be56327-2ac6-4dbd-b959-f74aaa3d5671)

**Comment by rmodrak** [comment]
Starting from a new install on my Mac, I was not able reproduce the above issue-- so it seems possible some slight change in dependencies might resolve it?  It seems possibly related to the matplotlib version?  

The following might help us debug further
-version of matplotlib installed in your environment
-full error traceback

Thanks for the report,
Ryan

**Comment by ZiguoFu** [comment]
@rmodrak Thanks for your kind reply! The problem has been solved after I opened a windows X-server software for my WSL system. Thanks again!

**Comment by rmodrak** [comment]
Hi Ziguo,  Thanks for the update, glad to hear it's working now
