### ISSUE TITLE
MTUQ Colab example crashes

### ISSUE THREAD

**Issue by SeismoFelix** [uafgeotools/mtuq#276]
Hello

I tried to run the MTUQ [Colab example](https://colab.research.google.com/drive/1UJWOompBz9MlJN0B6SoVKzF8Whz_1nPp#scrollTo=9yvc95JURnaz) and it seems that the branch that is cloned for the example is no longer available:

```
!git clone -b uq_matplotlib https://github.com/uafgeotools/mtuq.git --depth 1

Cloning into 'mtuq'...
warning: Could not find remote branch uq_matplotlib to clone.
fatal: Remote branch uq_matplotlib not found in upstream origin

```
Is it a new branch you recommend for running this example? 

Thanks.

**Comment by thurinj** [comment]
Thanks for reporting (sorry for the late reply on this item), the branch was indeed the preferred development branch at the time of the workshop. The changes have since then been merged to the main branch and the branch removed -- I've just updated the problematic cell in the workshop!
